package com.epam.liavitskaya.main.enums;

public enum CommandName {

	SIGN_IN, SIGN_OUT, REGISTRATION, CHANGE_STATUS, CHANGE_ROLE, ADD_NEW_BOOK, ADD_EDITED_BOOK, ORDER_BOOK, REVIEW_PROFILE, EDIT_PROFILE, EDIT_BOOK, WRITE_OFF_BOOK, DELETE_USER, DELETE_BOOK, SHOW_ALL_BOOKS, SHOW_ALL_USERS, WRONG_REQUEST

}
