package com.epam.liavitskaya.main.enums;

public enum CommandName {

	SIGN_IN, SIGN_OUT, REGISTRATION, ADD_NEW_BOOK, ADD_EDITED_BOOK, ORDER_BOOK, REVIEW_PROFILE, EDIT_PROFILE, EDIT_BOOK, AWAY_BOOK, DELETE_USER, DELETE_BOOK, SHOW_ALL_BOOKS, SHOW_ALL_USERS, WRONG_REQUEST

}
